using System.Text;

namespace Lutra.Core.Compose;

public static class ConfigGenerator
{
    public static string Generate(
        List<DetectedDatabase> databases,
        string backupDirectory,
        string? stateDirectory = null)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Generated by: lutra config generate");
        sb.AppendLine("# Review and adjust before use.");
        sb.AppendLine();
        sb.AppendLine($"backup_directory: {backupDirectory}");
        sb.AppendLine($"state_directory: {stateDirectory ?? Configuration.ConfigTemplates.GetDefaultStateDirectory()}");
        sb.AppendLine();
        sb.AppendLine("retention:");
        sb.AppendLine("  max_count: 10");
        sb.AppendLine("  max_age_days: 30");
        sb.AppendLine();
        sb.AppendLine("databases:");

        foreach (var db in databases)
        {
            sb.AppendLine($"  - name: {db.ServiceName}");
            sb.AppendLine($"    type: {db.Type.ToString().ToLowerInvariant()}");
            sb.AppendLine($"    container: {db.ContainerName}");

            if (db.DatabaseName is not null)
                sb.AppendLine($"    database: {db.DatabaseName}");
            else
                sb.AppendLine("    database: CHANGE_ME     # Could not detect database name");

            if (db.Username is not null)
                sb.AppendLine($"    username: {db.Username}");

            if (db.PasswordEnvVar is not null)
                sb.AppendLine($"    password_env: {db.PasswordEnvVar}");

            sb.AppendLine("    schedule: \"*-*-* 03:00:00\"");
            sb.AppendLine("    compression: gzip");

            if (db.Type == Configuration.DatabaseType.PostgreSql)
                sb.AppendLine("    format: custom");

            sb.AppendLine();
        }

        return sb.ToString().TrimEnd() + "\n";
    }

    public static string GenerateEnvTemplate(List<DetectedDatabase> databases)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by: lutra config generate");
        sb.AppendLine("# Set actual passwords below.");
        sb.AppendLine();

        foreach (var db in databases.Where(d => d.PasswordEnvVar is not null))
        {
            sb.AppendLine($"{db.PasswordEnvVar}=CHANGE_ME");
        }

        return sb.ToString();
    }
}
